### ISSUE TITLE
Nav items disappear on mobile

### ISSUE THREAD

**Issue by optikfluffel** [jenius/axis#155]
Hi, I just check the navigation mixin on my phone and saw that the navigation links simply disappear. Are there any plans making this more responsive (like the one from bootstrap)?

Thank :)

**Comment by jenius** [comment]
Hey sorry for the late response! I would be happy to accept a pull request to do this, but don't have the bandwidth to do it myself at the moment. Should just be one or two simple media queries :grinning:

**Comment by dbox** [comment]
I looked into this a little bit. Since there could be any number of items, there is really no breakpoint at which to switch it. We *could* pick an arbitrary mobile breakpoint to change to a stacked nav, but there would still be breakpoints along the way down where stuff would be cut off.

I say keep the mixin as you have it, and users does custom MQ's as necessary. Just my .02!

**Comment by jenius** [comment]
Fair enough, I'd agree with that. Let's close this out
