### ISSUE TITLE
Add theming system

### ISSUE THREAD

**Issue by FranzSkuffka** [jenius/axis#162]
using hashes and functions, so one can easily create interchangeable themes or even libraries.

**Comment by jenius** [comment]
So I'm not really super interested in adding this to axis, as it's more of a general utility belt and the UI stuff is just for basic prototyping with the intent that you'd be writing your own custom visuals for most sites rather than just ripping a theme like bootstrap. But I know @corysimmons is pretty interested in working on a library that does theming stuff, and has started some work on a couple -- maybe he would be able to tell you more!

**Comment by FranzSkuffka** [comment]
I think i did not express myself clear enough, i was having the idea of storing a $theme object containing keys like foreground, background, highlight etc and using functions like color('background') to get a specific color.
In short terms, abstracting away the actual names of colors to easily change the color scheme of the whole design.

**Comment by corysimmons** [comment]
I started work on a themeable UI kit but haven't touched it for a while. Feel free to check it out: https://github.com/corysimmons/switch

**Comment by jenius** [comment]
Hey @FranzSkuffka -- you can do this by just adding your own version of the `_settings.styl` file :grin:

**Comment by FranzSkuffka** [comment]
As always, you are right.
Don't be like that to me :D
