### ISSUE TITLE
Feature: Hover Gradient

### ISSUE THREAD

**Issue by abstracthat** [jenius/axis#171]
This is a handy one I use for buttons a lot. Pass a background color and it sets a gradient (using the Axis gradient mixin) as a background and a stronger gradient as a hover state. You can optionally pass a color for the text and set the the strength of the gradient for each state: normal, hover, active.

Should this go in `interaction.styl` with the other `hover-*` mixins or in `gradients.styl`?

```stylus
hover-gradient(background-color, color = #fff, strength = null, hover-strength = 15, active-strength = 5)
  hover-strength = unit(remove-unit(hover-strength), '%')
  active-strength = unit(remove-unit(active-strength), '%')

  gradient background-color strength
  color color

  &:hover
    gradient background-color hover-strength
    
  &:active
    gradient background-color active-strength
```

**Comment by jenius** [comment]
Hmm... so I handle this differently and you can see how in `glossy-button`. I really like transitions rather than abrupt swaps, and you can't transition between two gradients. However, you can allow transitions to work correctly with the gradient hover by actually just moving the gradient upwards using `background-position`. When you move the gradient up, it simulates a darkening of the gradient (the lighter part is pushed off the top and more dark is revealed), but smoothly animated and it keeps the gradient.

Have you tried out `glossy-button`? I feel like it solves the same concern, and additionally takes care of a bunch of other stuff (adjusting the text color automatically based on the background, rounding corners, text sizing, etc).

**Comment by abstracthat** [comment]
Ok, no problem. I don't use the axis buttons as I find I end up overwriting most of the styles. I'll have another look at how you structured glossy-button as I do like the idea of transitioning the background.
